name: Utilities-OG
authors: [ christianniehaus, NotAlexNoyle ]
version: '${version}'
api-version: '${apiVersion}'
main: net.trueog.utilitiesog.UtilitiesOG
depend: [ MiniPlaceholders, WorldGuard ]
commands:
  utilities:
    usage: /utilites
  togglephantoms:
    usage: /togglephantoms
  togglecramming:
    usage: /togglecramming
  ranks:
    usage: /ranks
  ping:
    usage: /ping
  bing:
    usage: /bing
  colorcodes:
    usage: /colorcodes

permissions:
  utilities.about:
    description: Permission to use the base /utilities command.
    default: op
  utilities.colorcodes:
    description: Permission to use the /colorcodes command.
    default: op
  utilities.togglephantoms:
    description: Permission to use the /togglephantoms command.
    default: op
  utilities.togglecramming:
    description: Permission to use the /togglecramming command.
    default: op
  utilities.ranks:
    description: Permission to use the /ranks command.
    default: op
  utilities.ping:
    description: Permission to use the /ping and /bing commands.
    default: op